name: Auto Deploy hugo

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.97.3
          extended: true
      - name: Build 
        run: hugo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # secret 中设置好私钥
          external_repository: bowenEI/bowenEI.github.io  # Page 仓库
          publish_branch: master  # Page 仓库的分支
          publish_dir: ./docs # 静态网页路径
          commit_message: ${{ github.event.head_commit.message }}
